server:
  port: 8761

spring:
  application:
    name: service-registry
  freemarker:
    template-loader-path: classpath:/templates/

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false